#!/usr/bin/env python

import os
from flask import Flask


port = os.getenv('RAINBOW_PORT_WEB_UI')

app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello World'


if __name__ == '__main__':
    app.run(port=port, debug=True)
