#!/usr/bin/env python

import os
from flask import Flask
from mid import Middle

port = int(os.getenv('RAINBOW_PORT_WEB_UI'))
root = int(os.getenv('RAINBOW_WEB_PATH'))

app = Flask(__name__)
app.wsgi_app=Middle(app.wsgi_app, prefix=root)

@app.route('/')
def index():
    return 'Hello World'


if __name__ == '__main__':
    app.run(port=port, debug=True)
