#!/bin/bash

watchdir=/shares/Public/text_files
while true; do
  filename=`inotifywait $watchdir -e close_write --format '%w%f'`
  sed 's/hi/hello/g' $filename > $filename.tmp && mv $filename.tmp $filename
done

